export type StackCategory = {
  name: string;
  area: string;
  logo: string; // /logos/*.svg
  color: string;
  body: string;
  chips: string[];
};

/**
 * Grounded in actual imports & dependency manifests across shipped apps
 * (Vael, Vow, AirPosture, Recite, Gut, Maintain, PayControl, Trace, ...).
 */
export const stackCategories: StackCategory[] = [
  {
    name: "Swift & SwiftUI",
    area: "iOS Core",
    logo: "/logos/swift.svg",
    color: "#F05138",
    body: "My native language. Clean, modular MVVM with the Observation framework and Swift Concurrency, interfaces with first-party polish, built to survive v2, v3 and v10.",
    chips: [
      "Swift 6",
      "SwiftUI",
      "UIKit",
      "SwiftData",
      "Combine",
      "Observation",
      "async/await",
      "Swift Charts",
      "CoreHaptics",
      "SpriteKit",
    ],
  },
  {
    name: "AI Engineering",
    area: "OpenAI · Claude · Gemini",
    logo: "/logos/openai.svg",
    color: "#C8B69B",
    body: "Production AI, not demos: multi-model systems with cost-tiered routing (4o for depth, 4o-mini for scale), agent pipelines, and vision, voice and reasoning grounded in the user's own data, engineered for reliability, latency and cost.",
    chips: [
      "OpenAI GPT-4o / 4o-mini",
      "Anthropic Claude",
      "Google Gemini",
      "Vision · Voice · Reasoning",
      "Agent pipelines",
      "Multi-model routing",
      "Prompt & cost engineering",
      "On-device Apple Intelligence",
    ],
  },
  {
    name: "Apple Ecosystem",
    area: "System Frameworks",
    logo: "/logos/apple.svg",
    color: "#E8E8ED",
    body: "The deep integrations that make an app feel like part of the OS, health, motion, screen time, weather, Siri, Live Activities, widgets and the Watch. This is where most iOS developers stop; it's where my apps start.",
    chips: [
      "HealthKit",
      "CoreMotion",
      "FamilyControls",
      "Screen Time API",
      "DeviceActivity",
      "WeatherKit",
      "CloudKit",
      "EventKit",
      "ActivityKit · Live Activities",
      "App Intents · Siri",
      "Vision",
      "Speech",
      "NaturalLanguage",
      "FoundationModels · Apple Intelligence",
      "WidgetKit",
      "watchOS · WatchConnectivity",
      "AVFoundation",
      "BackgroundTasks",
    ],
  },
  {
    name: "Firebase",
    area: "Realtime Backend",
    logo: "/logos/firebase.svg",
    color: "#FFCA28",
    body: "My default for realtime products, auth flows, live data sync, server logic and push, hardened with App Check and security rules that have passed real App Store scrutiny.",
    chips: [
      "Auth · Sign in with Apple",
      "Cloud Firestore",
      "Cloud Functions",
      "FCM Push",
      "App Check",
      "Security Rules",
      "Google Sign-In",
      "Analytics",
    ],
  },
  {
    name: "Supabase & Postgres",
    area: "Relational Backend",
    logo: "/logos/supabase.svg",
    color: "#3FCF8E",
    body: "Postgres power with a modern developer experience. My choice when an app needs relational data, row-level security and clean typed APIs from Swift.",
    chips: [
      "supabase-swift",
      "PostgreSQL",
      "Row-Level Security",
      "Edge Functions",
      "Storage",
      "Realtime",
    ],
  },
  {
    name: "Python & FastAPI",
    area: "Custom Backends",
    logo: "/logos/fastapi.svg",
    color: "#009688",
    body: "When an app needs its own brain, I build it: FastAPI services over PostgreSQL with Alembic migrations, structured logging and a pytest suite held above 80% coverage, fintech-grade discipline.",
    chips: [
      "FastAPI",
      "PostgreSQL",
      "Alembic",
      "pytest · 80%+ coverage",
      "structlog",
      "Pydantic",
      "REST API design",
    ],
  },
  {
    name: "Fintech & Monetization",
    area: "Payments",
    logo: "/logos/stripe.svg",
    color: "#635BFF",
    body: "Real money flows: Plaid bank connections, Stripe payments, StoreKit 2 subscriptions and RevenueCat paywalls, plus the App Store review process most developers fear, handled on every launch.",
    chips: [
      "Plaid",
      "Stripe",
      "StoreKit 2",
      "RevenueCat",
      "Paywall design",
      "Subscription analytics",
      "App Store review",
    ],
  },
  {
    name: "Security & DevOps",
    area: "Hardened by default",
    logo: "/logos/github.svg",
    color: "#34D399",
    body: "Every release ships through a security audit: hardened auth flows, strict Firestore and row-level security rules, App Check, encrypted local storage and secrets that never touch git. Plus the server administration and DevOps to keep production infrastructure locked down. Zero security incidents across every app I have shipped.",
    chips: [
      "Security audits",
      "Firestore security rules",
      "Row-Level Security",
      "App Check",
      "CryptoKit · Keychain",
      "Secrets management",
      "Server administration",
      "Deployment & monitoring",
      "Sentry",
    ],
  },
  {
    name: "Web & Full-Stack",
    area: "Next.js · React",
    logo: "/logos/nextdotjs.svg",
    color: "#E8E8ED",
    body: "Landing pages, dashboards and web companions for my apps, modern React on Vercel. This site is one of them.",
    chips: [
      "Next.js 16",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Vercel",
      "Framer Motion",
    ],
  },
  {
    name: "Craft & Tooling",
    area: "How it ships",
    logo: "/logos/xcode.svg",
    color: "#147EFB",
    body: "Designed in Figma, profiled in Instruments, monitored with Sentry, shipped through TestFlight. I run an AI-accelerated workflow (Claude Code, Codex) the way senior engineers run CI: it multiplies my speed, while architecture, review and judgment stay mine.",
    chips: [
      "Xcode · Instruments",
      "TestFlight",
      "Sentry",
      "CryptoKit · Keychain",
      "Figma",
      "Git · GitHub",
      "AI workflow · Claude Code · Codex",
      "CI discipline",
    ],
  },
];

/** Flat logo list for the home-page marquee. */
export const marqueeLogos: { name: string; logo: string }[] = [
  { name: "Swift", logo: "/logos/swift.svg" },
  { name: "Apple", logo: "/logos/apple.svg" },
  { name: "Xcode", logo: "/logos/xcode.svg" },
  { name: "Firebase", logo: "/logos/firebase.svg" },
  { name: "Supabase", logo: "/logos/supabase.svg" },
  { name: "PostgreSQL", logo: "/logos/postgresql.svg" },
  { name: "Python", logo: "/logos/python.svg" },
  { name: "FastAPI", logo: "/logos/fastapi.svg" },
  { name: "OpenAI", logo: "/logos/openai.svg" },
  { name: "Gemini", logo: "/logos/googlegemini.svg" },
  { name: "Stripe", logo: "/logos/stripe.svg" },
  { name: "Plaid", logo: "/logos/plaid.svg" },
  { name: "RevenueCat", logo: "/logos/revenuecat.svg" },
  { name: "Next.js", logo: "/logos/nextdotjs.svg" },
  { name: "React", logo: "/logos/react.svg" },
  { name: "TypeScript", logo: "/logos/typescript.svg" },
  { name: "Tailwind", logo: "/logos/tailwindcss.svg" },
  { name: "Node.js", logo: "/logos/nodedotjs.svg" },
  { name: "Vercel", logo: "/logos/vercel.svg" },
  { name: "Figma", logo: "/logos/figma.svg" },
  { name: "Git", logo: "/logos/git.svg" },
  { name: "GitHub", logo: "/logos/github.svg" },
];
